# ===========================================================================
# Spring
# ===========================================================================
spring.application.name=platform-server
# ===========================================================================
# Platform
# ===========================================================================
# \u5F00\u542F\u8C03\u8BD5\u6A21\u5F0F
platform.commons.debug=true
# IdWorker
platform.id.application-name=${spring.application.name}
platform.id.application-port=${server.port}
platform.id.application-pid=${PID}
platform.id.type=auto
platform.id.datacenter-id=1
platform.id.worker-id=1
# JWT
platform.jwt.secret=GerMgOsSNdAofwXfILuKAvWCpwGLObyj
platform.jwt.access-token-expire=3600
platform.jwt.refresh-token-expire=7200
# -------------------------------------------------------
# \u6587\u4EF6\u5B58\u50A8\u914D\u7F6E
# -------------------------------------------------------
platform.storage.type=oss
# minio
platform.storage.min.endpoint=http://127.0.0.1:9000
platform.storage.min.access-key=admin
platform.storage.min.secret-key=12345678
platform.storage.min.bucket-name=test
# cos
platform.storage.cos.endpoint=http://127.0.0.1:9000
platform.storage.cos.access-key=admin
platform.storage.cos.secret-key=12345678
platform.storage.cos.bucket-name=test
# oss
platform.storage.oss.endpoint=http://127.0.0.1:9000
platform.storage.oss.access-key-id=admin
platform.storage.oss.access-key-secret=12345678
platform.storage.oss.bucket-name=test
platform.storage.oss.domain=test
# ===========================================================================
# Spring Cache & Redis
# ===========================================================================
# Cache
spring.cache.type=redis
# Redis
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.database=11
# ===========================================================================
# Swagger
# ===========================================================================
springdoc.api-docs.enabled=false
springdoc.api-docs.groups.enabled=false
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=swagger.html
springdoc.swagger-ui.doc-expansion=false
# ===========================================================================
# DataBase & DataSource
# ===========================================================================
# \u6570\u636E\u6E90
spring.datasource.name=master
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=root
# ===========================================================================
