name: Build and Deploy
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: 'liberica'
                    java-version: '21'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v3
            -   name: Check Java and Gradle
                run: |
                    java -version
                    gradle -v
            -   name: Build with Gradle
                run: ./gradlew clean bootJar
            -   name: Deploy
                uses: wlixcc/SFTP-Deploy-Action@v1.2.4
                with:
                    username: ${{ secrets.SERVER_USER }}
                    server: ${{ secrets.SERVER_HOST }}
                    ssh_private_key: ${{ secrets.SERVER_KEY }}
                    local_path: 'platform-boot-server/app-server/build/libs/*'
                    remote_path: '/data/app/temp/app'
                    sftp_only: true
                    delete_remote_files: true
                    args: "-o ConnectTimeout=5"
